# Generated by Django 5.0.6 on 2024-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("neurology", "Neurology"),
                            ("orthopedics", "Orthopedics"),
                            ("pediatrics", "Pediatrics"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
