# Generated by Django 5.0.6 on 2024-06-16 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name": "data",
                "verbose_name_plural": "datas",
            },
        ),
    ]
